### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 2hands10fingers** [GoNZooo/vscode-environment-injector#4]
I know you've labeled this as an experiment, but my interest is peaked with it. You see, PyCharm has a feature to store your environment variables per the project. I was wondering that is something this could accomplish in the long-term?

**Comment by GoNZooo** [comment]
It has indeed mostly been an experiment and I've only used it maybe once or twice, but I think this should be possible already via the "Source/Read environment file" command. I've updated it now in a recent commit to use proper file dialogs for choosing the environment file. If you have a file called `dev.env` in your directory, you should be able to choose "Source environment file" in the command palette and choose the file.

With a file formatted as:

```
VAR1="some value here"
OTHER_VAR="42"
```

You should see these in your environment after sourcing that file.

Making a configuration per project would then be an issue of simply having the files at hand. It's also possible to maybe create a way of also allowing `export` to precede each of these lines, but since I don't really use the extension I don't know whether or not this is desirable for people.

It might be interesting to have the extension be configurable to automatically source files on load, but that would also require it to always be loaded (currently the activation events for the extension are the commands it exports, meaning we don't pollute peoples' sessions unnecessarily).

What were you thinking in terms of this feature, to have a configuration variable that lists your desired environment, or does a file you can source suffice?

**Comment by GoNZooo** [comment]
Since there's not much going on here I'll close this until further notice. I'm interested in maybe doing more with the extension, but the current situation works well enough for my purposes.
